name: fluttership
description: A Project Where I Share The Things I Love To Share [Null Safe]
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  measured_size: ^1.0.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.1
  firebase_storage: ^10.3.6
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.2.7
  

flutter_native_splash:
  color: "#0063dd"
  image: assets/logo.png #u must place logo.png in your assets folder
  android: true
  ios: true



flutter:
  uses-material-design: true
  assets:
  - assets/